apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-express-app
  annotations:
spec:
  rules:
  - host: "simple-express-app.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-express-app
            port:
              number: 80
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: simple-express-app2
            port:
              number: 80